export const LOGIN_SUBMIT_REQUEST = 'LOGIN_SUBMIT_REQUEST';
export const LOGIN_SUBMIT_SUCCESS = 'LOGIN_SUBMIT_SUCCESS';
export const LOGIN_SUBMIT_FAILURE = 'LOGIN_SUBMIT_FAILURE';

export const LOGOUT_SUBMIT_SUCCESS = 'LOGOUT_SUBMIT_SUCCESS';
export const TERMINAL_ITEM_ADD = 'TERMINAL_ITEM_ADD';
export const TERMINAL_ITEM_DELETE = 'TERMINAL_ITEM_DELETE';
